add_newline = false
command_timeout = 5000

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[✗](bold red)"
vicmd_symbol = "[V](bold green)"

[cmd_duration]
style = "bold yellow"

[directory]
style = "bold green"

[git_branch]
style = "bold blue"

[hostname]
disabled = true
style = "bold red"

[username]
format = "[$user]($style) on "
style_user = "bold purple"

[line_break]
disabled = true

[package]
disabled = true

[python]
disabled = true

[aws]
disabled = true

[gcloud]
disabled = true

[terraform]
disabled = true

[elixir]
disabled = true

[git_status]
disabled = true

[custom.elixir]
symbol = " "
command = "echo v$(elixir --short-version)"
files = ["mix.exs"]
style = "bold cyan"
format = "[$symbol](purple)[$output]($style) "
shell = ["bash", "--noprofile", "--norc"]

[directory.substitutions]
"com~apple~CloudDocs" = "/iCloud"
