[tools]
elixir = "1.18.0-otp-27"
erlang = "27.2"
gleam = "1.6.3"
neovim = "stable"
rust = "stable"
python = "3.13.1"
node = "latest"
"npm:@fsouza/prettierd" = "latest"
"npm:codeowners" = "latest"
"npm:eslint_d" = "latest"
"npm:mcp-hub" = "latest"
"npm:opencommit" = "latest"
"npm:pnpm" = "latest"
"npm:wscat" = "latest"
"npm:@anthropic-ai/claude-code" = "latest"
